server:
  servlet:
    context-path: /ps-trophy
spring:
  # Application 的配置项
  application:
    name: ps-trophy-web
  # Profile 的配置项
  profiles:
    active: local
  data:
    mongodb:
#      host: 121.43.101.188
#      port: 27017
#      authentication-database: admin
      database: trophy
#      username: admin
#      password: 753951
      uri: mongodb://admin:753951@121.43.101.188:27017/admin
  # SpringMVC 配置项
  mvc:
    throw-exception-if-no-handler-found: true # 匹配不到路径时，抛出 NoHandlerFoundException 异常
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-bean-definition-overriding: true
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

web:
  debug:
    #启用DebugInterceptor
    enabled: true
springdoc:
  version: '@springdoc.version@'
  useFqn: true
  model-and-view-allowed: true
  writer-with-default-pretty-printer: true
  cache:
    disabled: true
  api-docs:
    enabled: true
    groups:
      enabled: true
  # 扫描哪些包来生成OpenAPI文档, 多个包名用逗号分隔
  packages-to-scan: com.gdbyway.bpg.ip.emr
  packages-to-exclude: com.vincent
  paths-to-exclude: /ip-external-pub.api/**
  # 排除包匹配规则, 包名符合这些匹配规则会排除在OpenAPI文档之外, 多个规则用逗号分隔
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true